import type { DbCircle, DbMeetup } from './db'

export const MOCK_CIRCLES: DbCircle[] = [
  {
    id: 'mock-1',
    kind: 'УЖИН',
    time_short: 'сегодня в 20:00',
    title: 'Ужин у камина',
    hint: 'атмосферный ресторан · Тверская',
    place: 'Savva, Тверская',
    price: 2500,
    seats: 6,
    taken: 3,
    tilt: -1.2,
    bg: 'photo',
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&fit=crop&q=80',
  },
  {
    id: 'mock-2',
    kind: 'КОФЕ',
    time_short: 'завтра в 10:30',
    title: 'Утренний кофе',
    hint: 'лёгкий разговор за чашкой · Красный Октябрь',
    place: 'Kuznya, Балчуг',
    price: 800,
    seats: 5,
    taken: 3,
    tilt: 1.0,
    bg: 'photo',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700&fit=crop&q=80',
  },
  {
    id: 'mock-3',
    kind: 'ВЕЧЕР',
    time_short: 'в пятницу в 19:00',
    title: 'Вино и идеи',
    hint: 'тема: жизнь в большом городе',
    place: 'Blanc, Пресненская',
    price: 1800,
    seats: 6,
    taken: 3,
    tilt: 0.6,
    bg: 'photo',
    photo: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=700&fit=crop&q=80',
  },
  {
    id: 'mock-4',
    kind: 'УЖИН',
    time_short: 'в субботу в 19:30',
    title: 'Долгий ужин на Покровке',
    hint: 'неспешно, по-настоящему · Покровка',
    place: 'Bottega, Покровка',
    price: 1200,
    seats: 6,
    taken: 4,
    tilt: -0.8,
    bg: 'photo',
    photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=700&fit=crop&q=80',
  },
]

export const MOCK_MEETUPS: Record<string, DbMeetup> = {
  'mock-1': {
    id: 'meetup-mock-1',
    circle_id: 'mock-1',
    title: 'Ужин у камина',
    place: 'Savva, Тверская',
    date_label: 'сегодня в 20:00',
    scheduled_at: null,
    seats: 6,
    taken: 3,
    mood: 'оживлённо',
    status: 'upcoming',
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&fit=crop&q=80',
  },
  'mock-2': {
    id: 'meetup-mock-2',
    circle_id: 'mock-2',
    title: 'Утренний кофе',
    place: 'Kuznya, Балчуг',
    date_label: 'завтра в 10:30',
    scheduled_at: null,
    seats: 5,
    taken: 3,
    mood: 'спокойно',
    status: 'upcoming',
    photo: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=700&fit=crop&q=80',
  },
  'mock-3': {
    id: 'meetup-mock-3',
    circle_id: 'mock-3',
    title: 'Вино и идеи',
    place: 'Blanc, Пресненская',
    date_label: 'в пятницу в 19:00',
    scheduled_at: null,
    seats: 6,
    taken: 3,
    mood: 'с темой',
    status: 'upcoming',
    photo: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=700&fit=crop&q=80',
  },
  'mock-4': {
    id: 'meetup-mock-4',
    circle_id: 'mock-4',
    title: 'Долгий ужин на Покровке',
    place: 'Bottega, Покровка',
    date_label: 'в субботу в 19:30',
    scheduled_at: null,
    seats: 6,
    taken: 4,
    mood: 'оживлённо',
    status: 'upcoming',
    photo: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=700&fit=crop&q=80',
  },
}
